server:
  port: 9090
db:
  name: customerdb
spring:
  h2:
    console:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://vts-eureka-server:8761/eureka/
  instance:
    hostname: localhost

ui:
  serverUrl: http://localhost:4200/
management:
  endpoints:
    web:
      exposure:
        include: '*'
