spring:
  profiles:
    active: development
  application:
    name: vts-tracking-ui
  cloud:
    config:
      uri: http://localhost:5055

server.port: 9301

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hazelcast.max.no.heartbeat.seconds: 60

vaadin.url: /ui/
vaadin.urlMapping: ${vaadin.url}*
server.servlet.context-path: /

vehicle-service.name: vts-vehicle-service
vehicle-service.url: http://localhost:9091
