server:
  port: 9090
db:
  name: customerdb
spring:
  h2:
    console:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.4:8761/eureka/

ui:
  serverUrl: http://localhost:4200/
management:
  endpoints:
    web:
      exposure:
        include: '*'
