server:
  port: 9091
db:
  name: vehicledb
spring:
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
  mail:
    host: localhost
    port: 25
eureka:
  client:
    serviceUrl:
      defaultZone: http://vts-eureka-server:8761/eureka/
     
ui:
  serverUrl: http://localhost:4200/ 
management:
  endpoints:
    web:
      exposure:
        include: '*'
