spring:
  profiles:
    active: development
  application:
    name: vts-api-gateway
  cloud:
    config:
      uri: http://localhost:5055
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 5555
  
zuul:
  routes:
    vts-customer-service:
      path: /customer/**
      url: http://localhost:9090/
    vts-vehicle-service:
      path: /vehicle/**
      url: http://localhost:9091/
